### ISSUE TITLE
IBM-Swift/BlueSocket.git : dependency graph could not be satisfied

### ISSUE THREAD

**Issue by kansaraprateek** [IBM-Swift/Blitter#3]
Hi,

I am trying to build the Blitter project. And every time I am getting this same error. 
I also tried creating a new project and building it. Getting the same error every time.

Using Xcode 8.

![screen shot 2016-09-15 at 6 10 54 pm](https://cloud.githubusercontent.com/assets/8220848/18550074/ce04a604-7b6f-11e6-9efc-5e4a0b441685.png)

**Comment by rfdickerson** [comment]
@billabt You don't happen to know if anything's changed, do you?

**Comment by kansaraprateek** [comment]
No, I just started to try my hands on server side swift. Created a new projects added dependencies, and run it. Same issue every time.

using Xcode 8 with swift 3.0.

**Comment by JacopoMangiavacchi** [comment]
FYI it still compile on Linux

**Comment by rfdickerson** [comment]
Thanks for the info, @JacopoMangiavacchi

**Comment by rfdickerson** [comment]
@billabt , I think we have a problem. BlueSSLService version 0.10 points to BlueSocket 0.11 instead of BlueSocket 0.10.

**Comment by billabt** [comment]
Kitura is supposed to have upgraded to BlueSocket 0.11.  BlueSSLService is pointing at the latest BlueSocket as it always has.
